import { AlertTriangle, Download, FileText, PhilippinePeso, Plus, ReceiptText, RefreshCw, ShieldCheck, X } from 'lucide-react'
import { useCallback,useEffect,useMemo,useRef,useState,type FormEvent,type ReactNode } from 'react'
import { Button,PageHeader,SectionCard,StatCard,StatusBadge } from '../../components/ui'
import { currentMonth,fineDate,fineMoney,today } from './fine-format'
import { finesApi } from './fines-api'
import type { FineFilters,FineList,FineObligation,FineReceipt,FineTerm } from './types'

const field='h-11 w-full rounded-xl border border-[#0b5ea2]/20 bg-white px-3 text-sm text-[#0b5ea2] outline-none focus:ring-4 focus:ring-[#0b5ea2]/10'
const initial:FineFilters={search:'',status:'all',type:'all',period:'all',page:1,limit:100}
function requestKey(){return globalThis.crypto?.randomUUID?.()??`cash-${Date.now()}-${Math.random().toString(36).slice(2)}`}

export function AdminFinesPage(){
  const [filters,setFilters]=useState<FineFilters>(initial);const [data,setData]=useState<FineList|null>(null);const [terms,setTerms]=useState<FineTerm[]>([])
  const [error,setError]=useState('');const [notice,setNotice]=useState('');const [busy,setBusy]=useState(false)
  const [formError,setFormError]=useState('');const [auditReason,setAuditReason]=useState('')
  const [paying,setPaying]=useState<FineObligation|null>(null);const [adjusting,setAdjusting]=useState<FineObligation|null>(null);const [adjustmentType,setAdjustmentType]=useState<'Reduction'|'Waiver'|'Void'>('Reduction');const [showInfraction,setShowInfraction]=useState(false);const [receipt,setReceipt]=useState<FineReceipt|null>(null)
  const loadSequence=useRef(0)
  const paymentKey=useRef('')
  const load=useCallback(async(current=filters)=>{const sequence=++loadSequence.current;try{const result=await finesApi.adminList(current);if(sequence!==loadSequence.current)return;setData(result);setError('')}catch(cause){if(sequence!==loadSequence.current)return;setError(cause instanceof Error?cause.message:'Fine records are unavailable.')}},[filters])
  useEffect(()=>{void load(initial);void finesApi.adminTerms().then(setTerms).catch(()=>setTerms([]))},[]) // eslint-disable-line react-hooks/exhaustive-deps
  const controls=useMemo(()=>{
    if(filters.period==='all')return null
    if(filters.period==='daily')return <input type="date" value={filters.date??today()} onChange={(event)=>setFilters({...filters,date:event.target.value})} className={field}/>
    if(filters.period==='weekly')return <><input type="month" value={filters.month??currentMonth()} onChange={(event)=>setFilters({...filters,month:event.target.value})} className={field}/><select value={filters.week??1} onChange={(event)=>setFilters({...filters,week:Number(event.target.value)})} className={field}>{[1,2,3,4].map((week)=><option key={week} value={week}>Week {week}</option>)}</select></>
    if(filters.period==='monthly')return <input type="month" value={filters.month??currentMonth()} onChange={(event)=>setFilters({...filters,month:event.target.value})} className={field}/>
    if(filters.period==='semester')return <select value={filters.termId??''} onChange={(event)=>setFilters({...filters,termId:Number(event.target.value)})} className={field}><option value="">Select semester</option>{terms.map((term)=><option key={term.id} value={term.id}>{term.name} {term.academicYear}</option>)}</select>
    return <><input type="date" value={filters.from??today()} onChange={(event)=>setFilters({...filters,from:event.target.value})} className={field}/><input type="date" value={filters.to??today()} onChange={(event)=>setFilters({...filters,to:event.target.value})} className={field}/></>
  },[filters,terms])
  async function pay(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!paying||busy)return;const values=Object.fromEntries(new FormData(event.currentTarget).entries());setBusy(true);setFormError('');try{const created=await finesApi.pay({requestKey:paymentKey.current||(paymentKey.current=requestKey()),allocations:[{...(paying.fineId?{fineId:paying.fineId}:{lostBookReportId:paying.lostBookReportId!}),amount:Number(values.amount)}],notes:String(values.notes||'')||undefined});setReceipt(created);setPaying(null);setNotice(`Cash payment recorded under payment record ${created.receiptNumber}.`);await load()}catch(cause){setFormError(cause instanceof Error?cause.message:'The cash payment could not be recorded.')}finally{setBusy(false)}}
  async function adjust(event:FormEvent<HTMLFormElement>){
    event.preventDefault();if(!adjusting?.fineId||busy)return
    const values=Object.fromEntries(new FormData(event.currentTarget).entries());setBusy(true);setFormError('')
    try{
      if(adjustmentType==='Reduction'){
        const created=await finesApi.pay({requestKey:paymentKey.current||(paymentKey.current=requestKey()),allocations:[{fineId:adjusting.fineId,amount:Number(values.amount)}],notes:String(values.reason||'')||undefined})
        setReceipt(created);setNotice(`Partial cash payment recorded under payment record ${created.receiptNumber}.`)
      }else{
        await finesApi.adjust(adjusting.fineId,{type:adjustmentType,reason:String(values.reason)})
        setNotice(`${adjustmentType} recorded. No payment record was generated.`)
      }
      setAdjusting(null);setAuditReason('');setError('');await load()
    }catch(cause){setFormError(cause instanceof Error?cause.message:'The fine could not be updated.')}finally{setBusy(false)}
  }
  async function issue(event:FormEvent<HTMLFormElement>){event.preventDefault();const values=Object.fromEntries(new FormData(event.currentTarget).entries());setBusy(true);try{await finesApi.issueInfraction({schoolId:String(values.schoolId),category:String(values.category),amount:Number(values.amount),incidentAt:new Date(String(values.incidentAt)).toISOString(),location:String(values.location||''),details:String(values.details)});setShowInfraction(false);setNotice('The infraction fine was issued and the user was notified.');await load()}catch(cause){setError(cause instanceof Error?cause.message:'The infraction fine could not be issued.')}finally{setBusy(false)}}
  async function reverse(){if(!receipt)return;const reason=window.prompt('Enter the reason for reversing this cash receipt:')?.trim();if(!reason)return;setBusy(true);try{setReceipt(await finesApi.reverse(receipt.receiptId,reason));setNotice('The payment record was reversed and remains visible for audit.');await load()}catch(cause){setError(cause instanceof Error?cause.message:'The receipt could not be reversed.')}finally{setBusy(false)}}
  async function viewReceipt(receiptId:number){setBusy(true);setError('');try{setReceipt(await finesApi.receipt(receiptId,true))}catch(cause){setError(cause instanceof Error?cause.message:'The receipt could not be opened.')}finally{setBusy(false)}}
  async function downloadReport(){setError('');try{await finesApi.downloadReport(filters)}catch(cause){setError(cause instanceof Error?`PDF export failed: ${cause.message}`:'The PDF export failed.')}}
  return <>
    <PageHeader eyebrow="Financial records" title="Fines management" action={<div className="flex flex-wrap gap-2"><Button variant="secondary" onClick={()=>void load()}><RefreshCw size={16}/>Refresh</Button><Button variant="secondary" onClick={()=>setShowInfraction(true)}><Plus size={16}/>Issue infraction</Button><Button onClick={()=>void downloadReport()}><Download size={16}/>Export filtered PDF</Button></div>}/>
    {error?<div role="alert" className="mb-4 flex gap-2 rounded-xl bg-[#FFF200] p-4 font-bold text-[#0b5ea2]"><AlertTriangle size={18}/>{error}</div>:null}{notice?<div className="mb-4 rounded-xl border border-[#0b5ea2]/15 bg-[#0b5ea2]/5 p-4 font-semibold text-[#0b5ea2]">{notice}</div>:null}
    <SectionCard className="mb-5 p-4"><div className="grid gap-3 md:grid-cols-3 xl:grid-cols-6"><select value={filters.period} onChange={(event)=>setFilters({...filters,period:event.target.value as FineFilters['period']})} className={field}><option value="all">All records</option><option value="daily">Daily</option><option value="weekly">Weekly</option><option value="monthly">Monthly</option><option value="semester">Per semester</option><option value="custom">Custom dates</option></select>{controls}<select value={filters.type} onChange={(event)=>setFilters({...filters,type:event.target.value})} className={field}><option value="all">All fine types</option><option>Overdue</option><option>Infraction</option><option>Lost Book</option></select><select value={filters.status} onChange={(event)=>setFilters({...filters,status:event.target.value})} className={field}><option value="all">All statuses</option>{['Accruing','Unpaid','Partially Paid','Paid','Waived','Voided'].map((status)=><option key={status}>{status}</option>)}</select><input aria-label="Search fines and receipts" value={filters.search} onChange={(event)=>setFilters({...filters,search:event.target.value})} placeholder="Name, ID, receipt, or verification code" className={field}/><Button onClick={()=>void load()}>Apply filters</Button></div></SectionCard>
    <div className="mb-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><StatCard label="Assessed" value={fineMoney(data?.summary.assessed??0)} icon={PhilippinePeso}/><StatCard label="Outstanding" value={fineMoney(data?.summary.outstanding??0)} icon={AlertTriangle} tone="orange"/><StatCard label="Collected" value={fineMoney(data?.summary.collected??0)} icon={ReceiptText}/><StatCard label="Waived" value={fineMoney(data?.summary.waived??0)} icon={ShieldCheck}/><StatCard label="Accounts with balance" value={data?.summary.accountsWithBalance??0} icon={FileText}/></div>
    <SectionCard className="overflow-hidden"><div className="border-b border-[#0b5ea2]/15 p-5"><h2 className="font-bold text-[#0b5ea2]">Fine audit table</h2><p className="mt-1 text-xs text-[#0b5ea2]/60">{data?.range.label??'Selected period'} · {data?.pagination.total??0} records</p></div><div className="overflow-x-auto"><table className="w-full min-w-[1450px] text-left text-sm"><thead className="bg-[#0b5ea2] text-white"><tr>{['Fine','User','Type','Book / incident','Reason','Assessed','Paid','Waived','Balance','Receipt / verification','Status','Date','Actions'].map((value)=><th key={value} className="px-4 py-3">{value}</th>)}</tr></thead><tbody>{data?.items.length?data.items.map((item)=><tr key={item.id} className="border-b border-[#0b5ea2]/10"><td className="px-4 py-4 font-mono text-xs">{item.id}</td><td className="px-4 py-4"><strong>{item.userName}</strong><p className="text-xs text-[#0b5ea2]/60">{item.schoolId}</p></td><td className="px-4 py-4">{item.type}</td><td className="max-w-48 px-4 py-4 font-semibold">{item.title}</td><td className="max-w-64 px-4 py-4 text-[#0b5ea2]/70">{item.reason}</td><td className="px-4 py-4 font-bold">{fineMoney(item.assessed)}</td><td className="px-4 py-4">{fineMoney(item.paid)}</td><td className="px-4 py-4">{fineMoney(item.adjusted)}</td><td className="px-4 py-4 font-bold">{fineMoney(item.balance)}</td><td className="min-w-56 px-4 py-4">{item.receipts.length?<div className="space-y-2">{item.receipts.map((reference)=><button key={reference.receiptId} type="button" disabled={busy} onClick={()=>void viewReceipt(reference.receiptId)} className="block w-full rounded-lg border border-[#0b5ea2]/15 p-2 text-left hover:bg-[#0b5ea2]/5"><span className="block font-mono text-xs font-bold">{reference.receiptNumber}</span><span className="block font-mono text-xs text-[#0b5ea2]/65">{reference.verificationCode}</span>{reference.status==='Reversed'?<span className="mt-1 block text-[10px] font-bold">REVERSED</span>:null}</button>)}</div>:<span aria-label="No receipt">—</span>}</td><td className="px-4 py-4"><StatusBadge status={item.status}/></td><td className="px-4 py-4 text-xs">{fineDate(item.occurredAt)}</td><td className="px-4 py-4"><div className="flex gap-2"><Button disabled={!item.paymentAllowed} onClick={()=>{paymentKey.current=requestKey();setFormError('');setPaying(item)}}>Cash payment</Button>{item.fineId&&item.status!=='Accruing'&&!['Paid','Waived','Voided'].includes(item.status)?<Button variant="secondary" onClick={()=>{paymentKey.current=requestKey();setFormError('');setAuditReason('');setAdjustmentType('Reduction');setAdjusting(item)}}>Adjust</Button>:null}</div></td></tr>):<tr><td colSpan={13} className="p-12 text-center font-semibold">No fine records match these filters.</td></tr>}</tbody></table></div></SectionCard>
    {showInfraction?<Modal title="Issue behavioral infraction" close={()=>setShowInfraction(false)}><form onSubmit={issue} className="grid gap-3 sm:grid-cols-2"><input name="schoolId" required placeholder="Student or faculty school ID" className={field}/><select name="category" className={field}><option>Noise violation</option><option>Eating / food violation</option><option>Property misuse</option><option>Other</option></select><input name="amount" type="number" min="0.01" step="0.01" required placeholder="Fine amount" className={field}/><input name="incidentAt" type="datetime-local" required className={field}/><input name="location" placeholder="Location (optional)" className={`${field} sm:col-span-2`}/><textarea name="details" required minLength={10} placeholder="Document what happened" className={`${field} h-28 py-3 sm:col-span-2`}/><Button type="submit" disabled={busy} className="sm:col-span-2">Issue fine and notify user</Button></form></Modal>:null}
    {paying?<Modal title="Record cash payment" close={()=>setPaying(null)}><div className="mb-4 rounded-xl bg-[#0b5ea2]/5 p-4 text-sm"><strong>{paying.userName}</strong><p>{paying.title}</p><p className="mt-2 font-bold">Remaining balance: {fineMoney(paying.balance)}</p>{paying.type==='Lost Book'?<p className="mt-1 text-xs">Lost-book replacement charges must be paid in full.</p>:null}</div><form onSubmit={pay} className="space-y-3">{formError?<p role="alert" className="rounded-xl bg-[#FFF200] p-3 text-sm font-semibold text-[#0b5ea2]">{formError}</p>:null}<input name="amount" type="number" min="0.01" max={paying.balance} step="0.01" defaultValue={paying.balance.toFixed(2)} readOnly={paying.type==='Lost Book'} className={field}/><textarea name="notes" placeholder="Counter notes (optional)" className={`${field} h-24 py-3`}/><Button type="submit" disabled={busy} className="w-full">Record cash payment</Button></form></Modal>:null}
    {adjusting?<Modal title="Document fine adjustment" close={()=>setAdjusting(null)}><div className="mb-4 rounded-xl bg-[#0b5ea2]/5 p-4 text-sm">{adjustmentType==='Reduction'?<><strong>Partial cash payment</strong><p className="mt-1 text-[#0b5ea2]/70">The amount entered is the cash paid now. The unpaid amount remains as the student’s balance, and a payment record will be generated.</p></>:<><strong>No cash payment</strong><p className="mt-1 text-[#0b5ea2]/70">A waiver or void changes the fine without receiving cash, so it will not generate a payment record.</p></>}</div><form onSubmit={adjust} className="space-y-3">{formError?<p role="alert" className="rounded-xl bg-[#FFF200] p-3 text-sm font-semibold text-[#0b5ea2]">{formError}</p>:null}<label htmlFor="fine-adjustment-type" className="block text-sm font-bold">Adjustment type</label><select id="fine-adjustment-type" name="type" value={adjustmentType} onChange={(event)=>setAdjustmentType(event.target.value as 'Reduction'|'Waiver'|'Void')} className={field}><option value="Reduction">Reduction (partial payment)</option><option>Waiver</option><option>Void</option></select>{adjustmentType==='Reduction'?<><label htmlFor="fine-reduction-payment" className="block text-sm font-bold">Cash amount paid</label><input id="fine-reduction-payment" name="amount" type="number" min="0.01" max={adjusting.balance} step="0.01" required placeholder={`Maximum ${fineMoney(adjusting.balance)}`} className={field}/><p className="text-xs text-[#0b5ea2]/65">To pay half, enter {fineMoney(adjusting.balance/2)}.</p></>:null}<label htmlFor="fine-adjustment-reason" className="block text-sm font-bold">{adjustmentType==='Reduction'?'Payment notes':'Mandatory audit reason'}</label><textarea id="fine-adjustment-reason" name="reason" value={auditReason} onChange={(event)=>setAuditReason(event.target.value)} required={adjustmentType!=='Reduction'} minLength={adjustmentType==='Reduction'?undefined:10} placeholder={adjustmentType==='Reduction'?'Counter notes (optional)':'Explain why this adjustment is authorized'} className={`${field} h-28 py-3`}/><Button type="submit" disabled={busy} className="w-full">{adjustmentType==='Reduction'?'Record payment':`Record ${adjustmentType.toLowerCase()}`}</Button></form></Modal>:null}
    {receipt?<Modal title={`Payment record ${receipt.receiptNumber}`} close={()=>setReceipt(null)}><div className="space-y-3 text-sm text-[#0b5ea2]"><div className="rounded-xl bg-[#0b5ea2]/5 p-4"><div className="flex justify-between"><strong>{receipt.student.name}</strong><StatusBadge status={receipt.status}/></div><p>{receipt.student.schoolId}</p><p className="mt-3 text-xl font-bold">{fineMoney(receipt.amountReceived)}</p><p className="text-xs">Cash received by {receipt.receivedBy} · {fineDate(receipt.receivedAt)}</p><div className="mt-4 grid gap-1 rounded-lg border border-[#0b5ea2]/15 bg-white p-3"><span className="text-xs font-bold">Receipt number</span><span className="font-mono">{receipt.receiptNumber}</span><span className="mt-2 text-xs font-bold">Verification code</span><span className="font-mono">{receipt.verificationCode}</span></div></div>{receipt.allocations.map((item,index)=><div key={index} className="rounded-xl border border-[#0b5ea2]/15 p-3"><strong>{item.title}</strong><p>Paid {fineMoney(item.paid)} · Remaining {fineMoney(item.balanceAfter)}</p></div>)}<div className="flex flex-wrap gap-2"><Button onClick={()=>void finesApi.downloadReceipt(receipt.receiptId,receipt.receiptNumber,true).catch((cause)=>setError(cause instanceof Error?cause.message:'Receipt download failed.'))}><Download size={16}/>Download payment PDF</Button>{receipt.status==='Issued'?<Button variant="secondary" disabled={busy} onClick={()=>void reverse()}>Reverse receipt</Button>:null}</div></div></Modal>:null}
  </>
}

function Modal({title,close,children}:{title:string;close:()=>void;children:ReactNode}){return <div className="fixed inset-0 z-50 overflow-y-auto bg-[#0b5ea2]/75 p-4"><div className="mx-auto my-8 max-w-2xl rounded-2xl bg-white shadow-2xl"><header className="flex items-center justify-between border-b border-[#0b5ea2]/15 p-5"><h2 className="font-display text-xl font-bold text-[#0b5ea2]">{title}</h2><button aria-label="Close" onClick={close} className="p-2 text-[#0b5ea2]"><X/></button></header><div className="p-5">{children}</div></div></div>}
