import { Activity, Camera, Clock3, Download, RefreshCw, Search, Settings2, UserCheck, Users } from 'lucide-react'
import { useCallback, useEffect, useMemo, useState } from 'react'
import { Button, PageHeader, SectionCard, StatCard } from '../../components/ui'
import { AttendanceScannerModal } from './AttendanceScannerModal'
import { attendanceApi,type AcademicTerm,type AttendanceAnalytics,type AttendanceFilters,type AttendanceRow,type AttendanceSummary,type Capacity,type Pagination } from './attendance-api'

const today=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Manila',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())
const initial:AttendanceFilters={period:'daily',date:today,weekStart:today,year:Number(today.slice(0,4)),month:Number(today.slice(5,7)),academicTermId:'',q:'',role:'',purpose:'',presence:'',page:1,limit:25}
const field='h-10 rounded-xl border border-[#0b5ea2]/20 bg-white px-3 text-sm text-[#0b5ea2] outline-none focus:border-[#0b5ea2]'
const hourLabel=(hour:number)=>`${hour%12||12} ${hour<12?'AM':'PM'}`
const weekdays=['Mon','Tue','Wed','Thu','Fri','Sat']

export function AdminAttendancePage(){
  const[f,setF]=useState(initial),[terms,setTerms]=useState<AcademicTerm[]>([]),[summary,setSummary]=useState<AttendanceSummary|null>(null),[analytics,setAnalytics]=useState<AttendanceAnalytics|null>(null),[capacity,setCapacity]=useState<Capacity|null>(null),[rows,setRows]=useState<AttendanceRow[]>([]),[pagination,setPagination]=useState<Pagination>({page:1,limit:25,total:0,total_pages:0}),[loading,setLoading]=useState(true),[error,setError]=useState(''),[exporting,setExporting]=useState(false),[scannerOpen,setScannerOpen]=useState(false),[capacityOpen,setCapacityOpen]=useState(false),[capacityInput,setCapacityInput]=useState('80'),[capacityReason,setCapacityReason]=useState(''),[savingCapacity,setSavingCapacity]=useState(false)
  const key=useMemo(()=>JSON.stringify(f),[f])
  const load=useCallback(async()=>{setLoading(true);setError('');try{const[s,l,a,c]=await Promise.all([attendanceApi.summary(f),attendanceApi.logs(f),attendanceApi.analytics(f),attendanceApi.capacity()]);setSummary(s);setRows(l.rows);setPagination(l.pagination);setAnalytics(a);setCapacity(c);setCapacityInput(String(c.capacity))}catch(e){setError(e instanceof Error?e.message:'Unable to load attendance.')}finally{setLoading(false)}},[key])
  useEffect(()=>{void attendanceApi.terms().then(setTerms).catch(()=>setTerms([]))},[])
  useEffect(()=>{void load()},[load])
  useEffect(()=>{const timer=window.setInterval(()=>void attendanceApi.capacity().then(setCapacity).catch(()=>undefined),10000);return()=>window.clearInterval(timer)},[])
  const update=(patch:Partial<AttendanceFilters>)=>setF(v=>({...v,...patch,page:patch.page??1}))
  const exportPdf=async()=>{setExporting(true);setError('');try{await attendanceApi.downloadPdf(f)}catch(e){setError(e instanceof Error?e.message:'Unable to export report.')}finally{setExporting(false)}}
  const saveCapacity=async()=>{setSavingCapacity(true);setError('');try{const result=await attendanceApi.updateCapacity(Number(capacityInput),capacityReason);setCapacity(result);setCapacityOpen(false);setCapacityReason('')}catch(e){setError(e instanceof Error?e.message:'Unable to update capacity.')}finally{setSavingCapacity(false)}}
  const maxVisits=Math.max(1,...(analytics?.hourly.map(x=>x.visits)??[1]))
  return <>
    <PageHeader eyebrow="Facility monitoring" title="Attendance monitoring" action={<div className="flex flex-wrap gap-2"><Button variant="secondary" onClick={()=>setScannerOpen(true)}><Camera size={15}/>Scan QR</Button><Button variant="secondary" onClick={()=>setCapacityOpen(v=>!v)}><Settings2 size={15}/>Capacity</Button><Button variant="secondary" onClick={()=>void load()}><RefreshCw size={15}/>Refresh</Button><Button onClick={exportPdf} disabled={exporting}><Download size={15}/>{exporting?'Generating…':'Export'}</Button></div>}/>
    {error?<div className="mb-4 rounded-xl bg-[#FFF200] p-3 text-sm font-bold">{error}</div>:null}
    {capacityOpen?<SectionCard className="mb-5 p-5"><h2 className="font-display font-bold">Update maximum occupancy</h2><p className="mt-1 text-xs text-[#0b5ea2]/65">Changes take effect immediately. If the limit is below current occupancy, new entries are blocked until enough visitors leave.</p><div className="mt-4 grid gap-3 md:grid-cols-[180px_1fr_auto]"><label className="text-xs font-bold">Maximum occupants<input className={`${field} mt-1 w-full`} type="number" min="1" max="5000" value={capacityInput} onChange={e=>setCapacityInput(e.target.value)}/></label><label className="text-xs font-bold">Reason<input className={`${field} mt-1 w-full`} value={capacityReason} onChange={e=>setCapacityReason(e.target.value)} placeholder="Example: Updated fire-safety limit"/></label><Button className="self-end" onClick={()=>void saveCapacity()} disabled={savingCapacity}>{savingCapacity?'Saving…':'Save capacity'}</Button></div></SectionCard>:null}
    <SectionCard className="mb-5 p-4"><div className="grid gap-3 md:grid-cols-4"><select className={field} value={f.period} onChange={e=>update({period:e.target.value as AttendanceFilters['period']})}><option value="daily">Daily</option><option value="weekly">Weekly</option><option value="monthly">Monthly</option><option value="semester">Per semester</option></select>{f.period==='daily'?<input aria-label="Attendance date" className={field} type="date" value={f.date} onChange={e=>update({date:e.target.value})}/>:null}{f.period==='weekly'?<input aria-label="Week start" className={field} type="date" value={f.weekStart} onChange={e=>update({weekStart:e.target.value})}/>:null}{f.period==='monthly'?<><select className={field} value={f.month} onChange={e=>update({month:Number(e.target.value)})}>{Array.from({length:12},(_,i)=><option key={i+1} value={i+1}>{new Date(2026,i).toLocaleString('en',{month:'long'})}</option>)}</select><input className={field} type="number" min="2000" max="2100" value={f.year} onChange={e=>update({year:Number(e.target.value)})}/></>:null}{f.period==='semester'?<select className={field} value={f.academicTermId} onChange={e=>update({academicTermId:e.target.value})}><option value="">Select academic term</option>{terms.map(t=><option key={t.academic_term_id} value={t.academic_term_id}>{t.term_name} · {t.academic_year}</option>)}</select>:null}<label className={`${field} flex items-center gap-2`}><Search size={15}/><input className="w-full outline-none" placeholder="Name, ID, or email" value={f.q} onChange={e=>update({q:e.target.value})}/></label><select className={field} value={f.role} onChange={e=>update({role:e.target.value})}><option value="">All roles</option>{['Student','Faculty','Librarian','Admin'].map(v=><option key={v}>{v}</option>)}</select><select className={field} value={f.purpose} onChange={e=>update({purpose:e.target.value})}><option value="">All purposes</option>{['Library Visit','Study','Research','Book Borrowing','Printing','Photocopy'].map(v=><option key={v}>{v}</option>)}</select><select className={field} value={f.presence} onChange={e=>update({presence:e.target.value})}><option value="">All presence</option><option value="inside">Inside</option><option value="exited">Exited</option></select></div></SectionCard>
    <div className="mb-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><StatCard label="Visits" value={String(summary?.total_visits??0)} icon={Users}/><StatCard label="Unique visitors" value={String(summary?.unique_visitors??0)} icon={UserCheck}/><StatCard label="Currently inside" value={String(capacity?.current??0)} icon={Activity}/><StatCard label="Maximum capacity" value={String(capacity?.capacity??80)} note={`${capacity?.available??0} spaces available`} icon={Users}/><StatCard label="Peak hour" value={summary?.peak_hour??'—'} icon={Clock3}/></div>
    {capacity?.overCapacity?<div className="mb-5 rounded-xl bg-[#FFF200] p-4 font-bold">The library is over capacity. New check-ins are blocked until occupancy falls below {capacity.capacity}.</div>:null}
    <div className="mb-5 grid gap-5 xl:grid-cols-[1.1fr_.9fr]"><SectionCard className="p-5"><h2 className="font-display font-bold">Visits by hour</h2><p className="mt-1 text-xs text-[#0b5ea2]/65">Exact successful check-in timestamps for {analytics?.range.label??'the selected period'}</p><div className="mt-5 flex h-52 items-end gap-2 overflow-x-auto border-b border-[#0b5ea2]/20 px-2">{Array.from({length:14},(_,index)=>index+7).map(hour=>{const visits=analytics?.hourly.find(x=>x.hour===hour)?.visits??0;return <div key={hour} className="flex min-w-9 flex-1 flex-col items-center justify-end gap-1"><span className="text-[10px] font-bold">{visits||''}</span><div title={`${hourLabel(hour)}: ${visits} visits`} className={`w-full rounded-t-md ${visits===maxVisits&&visits>0?'bg-[#FFF200] ring-2 ring-[#0b5ea2]':'bg-[#0b5ea2]'}`} style={{height:`${Math.max(visits?8:2,visits/maxVisits*160)}px`}}/><span className="whitespace-nowrap text-[9px]">{hourLabel(hour)}</span></div>})}</div></SectionCard><SectionCard className="p-5"><h2 className="font-display font-bold">Weekly utilization</h2><p className="mt-1 text-xs text-[#0b5ea2]/65">Darker cells represent more check-ins.</p><div className="mt-5 space-y-2">{weekdays.map((day,weekday)=><div key={day} className="grid grid-cols-[34px_repeat(7,1fr)] items-center gap-1"><span className="text-[10px] font-bold">{day}</span>{[7,9,11,13,15,17,19].map(hour=>{const visits=analytics?.heatmap.filter(x=>x.weekday===weekday&&x.hour>=hour&&x.hour<hour+2).reduce((n,x)=>n+x.visits,0)??0;return <div key={hour} title={`${day} ${hourLabel(hour)}: ${visits} visits`} className={`h-7 rounded ${visits?visits>=maxVisits*.7?'bg-[#0b5ea2]':visits>=maxVisits*.3?'bg-[#0b5ea2]/55':'bg-[#0b5ea2]/20':'bg-[#0b5ea2]/5'}`}/>})}</div>)}<div className="ml-[38px] grid grid-cols-7 gap-1">{[7,9,11,13,15,17,19].map(h=><span key={h} className="text-center text-[9px]">{hourLabel(h)}</span>)}</div></div></SectionCard></div>
    <SectionCard><div className="flex items-center justify-between border-b border-[#0b5ea2]/15 p-5"><div><h2 className="font-bold">Attendance logs</h2><p className="text-xs text-[#0b5ea2]/65">{summary?.range.label??'Selected period'} · {pagination.total} records</p></div></div><div className="overflow-x-auto"><table className="w-full min-w-[850px] text-left text-sm"><thead className="bg-[#0b5ea2] text-white"><tr>{['Visitor','Role','Date','Time in','Time out','Purpose','Presence'].map(h=><th key={h} className="px-5 py-3 text-xs">{h}</th>)}</tr></thead><tbody>{loading?<tr><td colSpan={7} className="p-10 text-center">Loading attendance…</td></tr>:rows.length===0?<tr><td colSpan={7} className="p-10 text-center font-semibold">No attendance records match these filters.</td></tr>:rows.map(r=><tr key={r.id} className="border-b border-[#0b5ea2]/10"><td className="px-5 py-4"><b>{r.visitor_name}</b><p className="text-xs text-[#0b5ea2]/65">{r.school_id}</p></td><td className="px-5 py-4">{r.role}</td><td className="px-5 py-4">{r.attendance_date}</td><td className="px-5 py-4">{r.time_in}</td><td className="px-5 py-4">{r.time_out??'—'}</td><td className="px-5 py-4">{r.purpose}</td><td className="px-5 py-4"><span className={`rounded-full px-2 py-1 text-xs font-bold ${r.presence==='Inside'?'bg-[#FFF200]':'border border-[#0b5ea2]/20'}`}>{r.presence}</span></td></tr>)}</tbody></table></div><div className="flex justify-end gap-2 p-4"><Button variant="secondary" disabled={f.page<=1} onClick={()=>update({page:f.page-1})}>Previous</Button><span className="self-center text-xs font-bold">Page {pagination.page} of {Math.max(1,pagination.total_pages)}</span><Button variant="secondary" disabled={f.page>=pagination.total_pages} onClick={()=>update({page:f.page+1})}>Next</Button></div></SectionCard>
    <AttendanceScannerModal open={scannerOpen} onClose={()=>setScannerOpen(false)} onRecorded={()=>void load()}/>
  </>
}
