import { Camera, CheckCircle2, LogIn, LogOut, QrCode, Upload, X } from 'lucide-react'
import { useEffect, useRef, useState } from 'react'
import type { Html5Qrcode as Html5QrcodeInstance } from 'html5-qrcode'
import { Button } from '../../components/ui'
import { attendanceApi, type ScanConfirmation, type ScanResult } from './attendance-api'

const purposes=['Library Visit','Study','Research','Book Borrowing','Printing','Photocopy']
const readerId='smartlib-attendance-qr-reader'

export function AttendanceScannerModal({open,onClose,onRecorded}:{open:boolean;onClose:()=>void;onRecorded?:()=>void}){
  const scanner=useRef<Html5QrcodeInstance|null>(null),handling=useRef(false)
  const[mode,setMode]=useState<'check-in'|'check-out'>('check-in'),[purpose,setPurpose]=useState('Library Visit')
  const[scanning,setScanning]=useState(false),[payload,setPayload]=useState(''),[resolved,setResolved]=useState<ScanResult|null>(null),[confirmation,setConfirmation]=useState<ScanConfirmation|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false)
  const stop=async()=>{const instance=scanner.current;if(!instance)return;try{if(instance.isScanning)await instance.stop();await instance.clear()}catch{/* The camera may already have been released. */}finally{scanner.current=null;setScanning(false)}}
  const reset=async()=>{await stop();handling.current=false;setPayload('');setResolved(null);setConfirmation(null);setError('');setBusy(false)}
  useEffect(()=>{if(!open)void reset();return()=>{void stop()}},[open])
  const resolve=async(value:string)=>{if(handling.current)return;handling.current=true;setError('');setBusy(true);try{await stop();const result=await attendanceApi.resolveScan(value);setPayload(value);setResolved(result);if(result.openVisit)setMode('check-out')}catch(e){setError(e instanceof Error?e.message:'Unable to verify this QR code.');handling.current=false}finally{setBusy(false)}}
  const start=async()=>{await reset();setError('');try{const{Html5Qrcode,Html5QrcodeSupportedFormats}=await import('html5-qrcode');const cameras=await Html5Qrcode.getCameras();if(!cameras.length)throw new Error('No camera was found on this device.');const instance=new Html5Qrcode(readerId,{formatsToSupport:[Html5QrcodeSupportedFormats.QR_CODE],verbose:false});scanner.current=instance;setScanning(true);const preferred=cameras.find(c=>/back|rear|environment/i.test(c.label))??cameras[0];await instance.start(preferred.id,{fps:10,qrbox:{width:240,height:240}},decoded=>void resolve(decoded),()=>undefined)}catch(e){await stop();setError(e instanceof Error?e.message:'Camera access could not be started. Use HTTPS and allow camera permission.')}}
  const upload=async(file:File|null)=>{if(!file)return;await reset();setBusy(true);setError('');try{const{Html5Qrcode,Html5QrcodeSupportedFormats}=await import('html5-qrcode');const instance=new Html5Qrcode(readerId,{formatsToSupport:[Html5QrcodeSupportedFormats.QR_CODE],verbose:false});scanner.current=instance;const decoded=await instance.scanFile(file,true);await resolve(decoded)}catch(e){setError(e instanceof Error?e.message:'No valid QR code was found in that image.');handling.current=false}finally{setBusy(false);await stop()}}
  const confirm=async()=>{if(!payload)return;setBusy(true);setError('');try{const data=mode==='check-in'?await attendanceApi.checkIn(payload,purpose,crypto.randomUUID().replaceAll('-','')):await attendanceApi.checkOut(payload);setConfirmation(data);setResolved(null);onRecorded?.()}catch(e){setError(e instanceof Error?e.message:'Attendance could not be recorded.')}finally{setBusy(false)}}
  if(!open)return null
  return <div className="fixed inset-0 z-[80] flex items-center justify-center bg-[#0b5ea2]/55 p-4 backdrop-blur-sm" role="dialog" aria-modal="true" aria-label="Attendance QR scanner"><div className="max-h-[92vh] w-full max-w-xl overflow-y-auto rounded-3xl bg-white shadow-2xl"><div className="flex items-center justify-between border-b border-[#0b5ea2]/15 p-5"><div><p className="text-[10px] font-bold uppercase tracking-[.18em] text-[#0b5ea2]/55">Library entrance</p><h2 className="mt-1 font-display text-xl font-bold">Scan attendance QR</h2></div><button onClick={onClose} aria-label="Close attendance scanner" className="rounded-xl p-2 hover:bg-[#0b5ea2]/5"><X/></button></div><div className="space-y-4 p-5">
    {confirmation?<div className="rounded-2xl bg-[#FFF200] p-5 text-center"><CheckCircle2 className="mx-auto" size={36}/><h3 className="mt-3 font-display text-xl font-bold">{confirmation.message}</h3><p className="mt-2 text-sm">{confirmation.visitor.name} · {confirmation.visitor.schoolId}</p><p className="mt-1 text-xs">Current occupancy: {confirmation.occupancy.current} of {confirmation.occupancy.capacity}</p><Button className="mt-5" onClick={()=>void reset()}>Scan another visitor</Button></div>:<>
      <div className="grid grid-cols-2 gap-2"><button onClick={()=>setMode('check-in')} className={`rounded-xl border p-3 text-sm font-bold ${mode==='check-in'?'border-[#0b5ea2] bg-[#0b5ea2] text-white':'border-[#0b5ea2]/20'}`}><LogIn className="mr-2 inline" size={16}/>Check in</button><button onClick={()=>setMode('check-out')} className={`rounded-xl border p-3 text-sm font-bold ${mode==='check-out'?'border-[#0b5ea2] bg-[#0b5ea2] text-white':'border-[#0b5ea2]/20'}`}><LogOut className="mr-2 inline" size={16}/>Check out</button></div>
      {mode==='check-in'?<label className="block text-xs font-bold">Purpose of visit<select value={purpose} onChange={e=>setPurpose(e.target.value)} className="mt-1 h-11 w-full rounded-xl border border-[#0b5ea2]/20 bg-white px-3 text-sm">{purposes.map(v=><option key={v}>{v}</option>)}</select></label>:null}
      <div id={readerId} className="min-h-16 overflow-hidden rounded-2xl border border-[#0b5ea2]/15 bg-[#0b5ea2]/5"/>
      {!resolved?<div className="grid gap-2 sm:grid-cols-2"><Button onClick={()=>void start()} disabled={scanning||busy}><Camera size={16}/>{scanning?'Camera active':'Start camera'}</Button><label className="inline-flex h-10 cursor-pointer items-center justify-center gap-2 rounded-xl border border-[#0b5ea2]/20 px-4 text-sm font-semibold"><Upload size={16}/>Scan saved image<input type="file" accept="image/*" className="sr-only" onChange={e=>void upload(e.target.files?.[0]??null)}/></label></div>:<div className="rounded-2xl border border-[#0b5ea2]/15 p-4"><div className="flex items-start gap-3"><span className="rounded-xl bg-[#FFF200] p-2"><QrCode size={20}/></span><div><h3 className="font-bold">{resolved.visitor.name}</h3><p className="text-sm">{resolved.visitor.schoolId} · {resolved.visitor.role}</p><p className="mt-1 text-xs text-[#0b5ea2]/65">{resolved.openVisit?'Currently inside the library':'Ready to check in'} · Occupancy {resolved.occupancy.current}/{resolved.occupancy.capacity}</p></div></div><div className="mt-4 grid grid-cols-2 gap-2"><Button variant="secondary" onClick={()=>void reset()}>Scan again</Button><Button onClick={()=>void confirm()} disabled={busy}>{busy?'Saving…':mode==='check-in'?'Confirm entry':'Confirm exit'}</Button></div></div>}
    </>}
    {error?<div className="rounded-xl bg-[#FFF200] p-3 text-sm font-bold" role="alert">{error}</div>:null}
  </div></div></div>
}
