import { Download, Droplets, PackageOpen, Plus, RefreshCw } from 'lucide-react'
import { useEffect, useState, type FormEvent } from 'react'
import { Button, PageHeader, SectionCard, StatCard, StatusBadge } from '../../components/ui'
import { printingApi, type ExpenseSummary, type FinanceFilters, type FinancePeriod, type RestockEntry, type RevenueEntry, type RevenueSummary, type StockUsageEntry, type SupplyData } from './printing-api'

type Selection={kind:'ink'|'paper';id:number;name:string;unit:'bottles'|'reams';current:number}
type UsageSelection={kind:'ink'|'paper';id:number;name:string;current:number}
const input='mt-1 h-11 w-full rounded-xl border border-[#0b5ea2]/20 bg-[#FFFFFF] px-3 text-[#0b5ea2] outline-none focus:border-[#0b5ea2]'
function manilaToday(){const parts=new Intl.DateTimeFormat('en-US',{timeZone:'Asia/Manila',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date()),values=Object.fromEntries(parts.map(part=>[part.type,part.value]));return `${values.year}-${values.month}-${values.day}`}
function money(value:number|string|undefined){return `₱${Number(value??0).toFixed(2)}`}
function whole(value:number|string|null|undefined,fallback='0'){return value==null?fallback:String(Math.trunc(Number(value)))}
function initialFilters():FinanceFilters{const date=manilaToday();return{period:'monthly',date,month:date.slice(0,7),week:Math.min(4,Math.ceil(Number(date.slice(8,10))/7))}}

export function AdminPrintSuppliesPage(){
  const [data,setData]=useState<SupplyData|null>(null),[selected,setSelected]=useState<Selection|null>(null),[usage,setUsage]=useState<UsageSelection|null>(null),[showInk,setShowInk]=useState(false)
  const [newInk,setNewInk]=useState({cartridge_type:'',color_variation:'Black',available_bottles:1,low_stock_threshold_bottles:1,cost_per_bottle:''})
  const [quantity,setQuantity]=useState(1),[unitCost,setUnitCost]=useState('')
  const [filters,setFilters]=useState<FinanceFilters>(initialFilters),[revenue,setRevenue]=useState<RevenueSummary|null>(null),[revenueEntries,setRevenueEntries]=useState<RevenueEntry[]>([]),[expenses,setExpenses]=useState<ExpenseSummary|null>(null),[restocks,setRestocks]=useState<RestockEntry[]>([]),[usageEntries,setUsageEntries]=useState<StockUsageEntry[]>([])
  const [loading,setLoading]=useState(true),[reportLoading,setReportLoading]=useState(true),[saving,setSaving]=useState(false),[exporting,setExporting]=useState<'revenue'|'stock'|'inventory'|null>(null)
  const [error,setError]=useState(''),[success,setSuccess]=useState('')
  const loadSupplies=async()=>{setLoading(true);try{setData(await printingApi.supplies())}catch(e){setError(e instanceof Error?e.message:'Unable to load print supplies.')}finally{setLoading(false)}}
  const loadReports=async(current=filters)=>{setReportLoading(true);try{const[r,re,ex,rh,uh]=await Promise.all([printingApi.revenueSummary(current),printingApi.revenueEntries(current),printingApi.expenseSummary(current),printingApi.restockHistory(current),printingApi.stockUsage()]);setRevenue(r);setRevenueEntries(re);setExpenses(ex);setRestocks(rh);setUsageEntries(uh)}catch(e){setError(e instanceof Error?e.message:'Unable to load printing reports.')}finally{setReportLoading(false)}}
  useEffect(()=>{setError('');void loadSupplies()},[])
  useEffect(()=>{setError('');void loadReports(filters)},[filters.period,filters.date,filters.month,filters.week])
  const openRestock=(selection:Selection)=>{setSelected(selection);setQuantity(1);setUnitCost('');setError('');setSuccess('')}
  const submitRestock=async(e:FormEvent)=>{e.preventDefault();if(!selected)return;setSaving(true);setError('');setSuccess('');try{await printingApi.restock(selected.kind,selected.id,{quantity,unit_cost:Number(unitCost)});setSuccess(`${quantity} ${selected.unit} added to ${selected.name}.`);setSelected(null);await Promise.all([loadSupplies(),loadReports()])}catch(err){setError(err instanceof Error?err.message:'Unable to save the restock. No stock was changed.')}finally{setSaving(false)}}
  const confirmUsage=async()=>{if(!usage)return;setSaving(true);setError('');setSuccess('');try{if(usage.kind==='ink')await printingApi.useInkBottle(usage.id);else await printingApi.openPaperReam(usage.id);setSuccess(usage.kind==='ink'?`One ${usage.name} bottle was recorded as loaded into the printer.`:`One ${usage.name} ream was recorded as opened.`);setUsage(null);await Promise.all([loadSupplies(),loadReports()])}catch(err){setError(err instanceof Error?err.message:'Unable to update the supply stock.')}finally{setSaving(false)}}
  const addInk=async(e:FormEvent)=>{e.preventDefault();setSaving(true);setError('');setSuccess('');try{await printingApi.createInk({...newInk,cost_per_bottle:Number(newInk.cost_per_bottle)});setShowInk(false);setSuccess(`${newInk.available_bottles} bottles of ${newInk.cartridge_type} ink added.`);setNewInk({cartridge_type:'',color_variation:'Black',available_bottles:1,low_stock_threshold_bottles:1,cost_per_bottle:''});await Promise.all([loadSupplies(),loadReports()])}catch(err){setError(err instanceof Error?err.message:'Unable to add ink stock. No stock was changed.')}finally{setSaving(false)}}
  const refresh=async()=>{setError('');await Promise.all([loadSupplies(),loadReports()])}
  const exportReport=async(kind:'revenue'|'stock'|'inventory')=>{setExporting(kind);setError('');try{if(kind==='revenue')await printingApi.revenueReport(filters);else if(kind==='stock')await printingApi.stockExpenseReport(filters);else await printingApi.supplyReport()}catch(e){setError(e instanceof Error?e.message:'Unable to export the report.')}finally{setExporting(null)}}
  const setMonth=(month:string)=>setFilters(value=>({...value,month,date:`${month}-01`}))
  const totalExpense=Number((quantity*Number(unitCost||0)).toFixed(2))
  return <>
    <PageHeader eyebrow="Printing inventory" title="Print supplies" action={<div className="flex flex-wrap gap-2"><Button variant="secondary" disabled={Boolean(exporting)||loading} onClick={()=>void exportReport('inventory')}><Download size={15}/>{exporting==='inventory'?'Generating…':'Export current stock PDF'}</Button><Button variant="secondary" onClick={()=>setShowInk(true)}><Plus size={15}/>Add ink stock</Button><Button variant="secondary" onClick={()=>void refresh()}><RefreshCw size={15}/>Refresh</Button></div>}/>
    {error&&<div className="mb-4 rounded-xl bg-[#FFF200] p-3 text-sm font-bold text-[#0b5ea2]">{error}</div>}
    {success&&<div className="mb-4 rounded-xl border border-[#0b5ea2] bg-[#FFFFFF] p-3 text-sm font-bold text-[#0b5ea2]">{success}</div>}
    <div className="mb-5 grid gap-5 xl:grid-cols-2">
      <SectionCard className="overflow-hidden"><div className="border-b border-[#0b5ea2]/15 p-5"><h2 className="font-bold text-[#0b5ea2]">Ink bottles</h2></div><div className="divide-y divide-[#0b5ea2]/10">{loading?<p className="p-8 text-center text-[#0b5ea2]">Loading…</p>:data?.ink.length===0?<p className="p-8 text-center font-semibold text-[#0b5ea2]">No ink bottle records.</p>:data?.ink.map(row=><div key={row.ink_id} className="flex flex-wrap items-center gap-3 p-4"><span className="rounded-xl bg-[#0b5ea2]/5 p-3 text-[#0b5ea2]"><Droplets size={19}/></span><div className="min-w-44 flex-1"><b className="text-[#0b5ea2]">{row.cartridge_type} · {row.color_variation}</b><p className="text-xs text-[#0b5ea2]/65">Low-stock alert at {row.low_stock_threshold_bottles} bottles</p></div><div className="text-right"><p className="text-xl font-bold text-[#0b5ea2]">{row.available_bottles}</p><p className="text-xs text-[#0b5ea2]/65">unopened bottles</p></div><StatusBadge status={Number(row.is_low)?'Low stock':'In stock'}/><Button variant="secondary" disabled={Number(row.available_bottles)<1} onClick={()=>setUsage({kind:'ink',id:row.ink_id,name:`${row.cartridge_type} ${row.color_variation}`,current:Number(row.available_bottles)})}>Use one bottle</Button><Button onClick={()=>openRestock({kind:'ink',id:row.ink_id,name:`${row.cartridge_type} ${row.color_variation}`,unit:'bottles',current:Number(row.available_bottles)})}>Restock</Button></div>)}</div></SectionCard>
      <SectionCard className="overflow-hidden"><div className="border-b border-[#0b5ea2]/15 p-5"><h2 className="font-bold text-[#0b5ea2]">Bond paper</h2></div><div className="divide-y divide-[#0b5ea2]/10">{loading?<p className="p-8 text-center text-[#0b5ea2]">Loading…</p>:data?.paper.length===0?<p className="p-8 text-center font-semibold text-[#0b5ea2]">No paper records.</p>:data?.paper.map(row=><div key={row.paper_stock_id} className="flex flex-wrap items-center gap-3 p-4"><span className="rounded-xl bg-[#0b5ea2]/5 p-3 text-[#0b5ea2]"><PackageOpen size={19}/></span><div className="min-w-44 flex-1"><b className="text-[#0b5ea2]">{row.paper_size_dimension} bond paper</b><p className="text-xs text-[#0b5ea2]/65">Low-stock alert at {row.low_stock_threshold_reams} reams</p></div><div className="text-right"><p className="text-xl font-bold text-[#0b5ea2]">{Number(row.unopened_reams)}</p><p className="text-xs text-[#0b5ea2]/65">unopened reams</p></div><StatusBadge status={Number(row.is_low)?'Low stock':'In stock'}/><Button variant="secondary" disabled={Number(row.unopened_reams)<1} onClick={()=>setUsage({kind:'paper',id:row.paper_stock_id,name:`${row.paper_size_dimension} bond paper`,current:Number(row.unopened_reams)})}>Open one ream</Button><Button onClick={()=>openRestock({kind:'paper',id:row.paper_stock_id,name:`${row.paper_size_dimension} bond paper`,unit:'reams',current:Number(row.unopened_reams)})}>Restock</Button></div>)}</div></SectionCard>
    </div>
    <SectionCard className="mb-5 p-4"><div className="flex flex-col gap-3 lg:flex-row lg:items-end"><label className="text-xs font-bold text-[#0b5ea2]">Report period<select className={input} value={filters.period} onChange={e=>setFilters(value=>({...value,period:e.target.value as FinancePeriod}))}><option value="daily">Daily</option><option value="weekly">Weekly</option><option value="monthly">Monthly</option></select></label>{filters.period==='daily'?<label className="text-xs font-bold text-[#0b5ea2]">Date<input className={input} type="date" value={filters.date} onChange={e=>setFilters(value=>({...value,date:e.target.value,month:e.target.value.slice(0,7)}))}/></label>:<label className="text-xs font-bold text-[#0b5ea2]">Month<input className={input} type="month" value={filters.month} onChange={e=>setMonth(e.target.value)}/></label>}{filters.period==='weekly'&&<label className="text-xs font-bold text-[#0b5ea2]">Week in month<select className={input} value={filters.week} onChange={e=>setFilters(value=>({...value,week:Number(e.target.value)}))}>{[1,2,3,4].map(week=><option key={week} value={week}>Week {week}</option>)}</select></label>}<p className="pb-3 text-xs font-semibold text-[#0b5ea2]/65">{reportLoading?'Loading selected period…':revenue?.label??'Select a period'}</p><div className="flex flex-wrap gap-2 lg:ml-auto"><Button variant="secondary" disabled={Boolean(exporting)} onClick={()=>void exportReport('revenue')}><Download size={15}/>{exporting==='revenue'?'Generating…':'Export revenue PDF'}</Button><Button disabled={Boolean(exporting)} onClick={()=>void exportReport('stock')}><Download size={15}/>{exporting==='stock'?'Generating…':'Export stock expenses PDF'}</Button></div></div></SectionCard>
    <div className="mb-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><StatCard label="Paid requests" value={String(revenue?.paid_requests??0)}/><StatCard label="Sheets" value={String(revenue?.total_sheets??0)} icon={PackageOpen}/><StatCard label="Copies" value={String(revenue?.total_copies??0)} icon={PackageOpen}/><StatCard label="Printing revenue" value={money(revenue?.total_revenue)}/></div>
    <SectionCard className="mb-5 overflow-hidden"><div className="border-b border-[#0b5ea2]/15 p-5"><h2 className="font-bold text-[#0b5ea2]">Revenue details</h2></div><div className="overflow-x-auto"><table className="w-full min-w-[1050px] text-left text-sm"><thead className="bg-[#0b5ea2] text-[#FFFFFF]"><tr>{['Date','Request','Student','File','Type','Paper','Pages','Copies','Sheets','Revenue'].map(label=><th key={label} className="px-3 py-3 text-xs uppercase">{label}</th>)}</tr></thead><tbody className="divide-y divide-[#0b5ea2]/10">{reportLoading?<tr><td colSpan={10} className="p-8 text-center text-[#0b5ea2]">Loading revenue…</td></tr>:revenueEntries.length===0?<tr><td colSpan={10} className="p-8 text-center font-semibold text-[#0b5ea2]">No paid printing requests for this period.</td></tr>:revenueEntries.map(row=><tr key={row.request_id} className="text-[#0b5ea2]"><td className="whitespace-nowrap px-3 py-3">{new Date(row.received_at).toLocaleString()}</td><td className="px-3 py-3">#{row.request_id}</td><td className="px-3 py-3 font-semibold">{row.full_name}<small className="block font-normal">{row.school_id}</small></td><td className="px-3 py-3">{row.file_name}</td><td className="px-3 py-3">{row.print_type}</td><td className="px-3 py-3">{row.paper_size}</td><td className="px-3 py-3">{row.page_count}</td><td className="px-3 py-3">{row.number_of_copies}</td><td className="px-3 py-3">{row.total_sheets}</td><td className="px-3 py-3 font-bold">{money(row.amount_paid)}</td></tr>)}</tbody></table></div></SectionCard>
    <div className="mb-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><StatCard label="Restock entries" value={String(expenses?.restock_entries??0)} icon={RefreshCw}/><StatCard label="Ink restock costs" value={money(expenses?.ink_expenses)} icon={Droplets}/><StatCard label="Paper restock costs" value={money(expenses?.paper_expenses)} icon={PackageOpen}/><StatCard label="Total restock expenses" value={money(expenses?.total_expenses)}/></div>
    <SectionCard className="mb-5 overflow-hidden"><div className="border-b border-[#0b5ea2]/15 p-5"><h2 className="font-bold text-[#0b5ea2]">Restock history</h2></div><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-sm"><thead className="bg-[#0b5ea2] text-[#FFFFFF]"><tr>{['Date','Type','Supply','Quantity','Unit cost','Total expense','Before','After','Recorded by'].map(label=><th key={label} className="px-3 py-3 text-xs uppercase">{label}</th>)}</tr></thead><tbody className="divide-y divide-[#0b5ea2]/10">{reportLoading?<tr><td colSpan={9} className="p-8 text-center text-[#0b5ea2]">Loading restock history…</td></tr>:restocks.length===0?<tr><td colSpan={9} className="p-8 text-center font-semibold text-[#0b5ea2]">No restocks for this period.</td></tr>:restocks.map((row,index)=><tr key={`${row.created_at}-${index}`} className="text-[#0b5ea2]"><td className="whitespace-nowrap px-3 py-3">{new Date(row.created_at).toLocaleString()}</td><td className="px-3 py-3">{row.supply_type}</td><td className="px-3 py-3 font-semibold">{row.supply_name}</td><td className="px-3 py-3">{whole(row.quantity)} {row.unit}</td><td className="px-3 py-3">{money(row.unit_cost)}</td><td className="px-3 py-3 font-bold">{money(row.total_expense)}</td><td className="px-3 py-3">{whole(row.balance_before,'Legacy')}</td><td className="px-3 py-3">{whole(row.balance_after,'Legacy')}</td><td className="px-3 py-3">{row.recorded_by??'System'}</td></tr>)}</tbody></table></div></SectionCard>
    <SectionCard className="overflow-hidden"><div className="border-b border-[#0b5ea2]/15 p-5"><h2 className="font-bold text-[#0b5ea2]">Recent manual stock usage</h2></div><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-[#0b5ea2] text-[#FFFFFF]"><tr>{['Date','Type','Supply','Action','Quantity','Before','After','Recorded by'].map(label=><th key={label} className="px-3 py-3 text-xs uppercase">{label}</th>)}</tr></thead><tbody className="divide-y divide-[#0b5ea2]/10">{usageEntries.length===0?<tr><td colSpan={8} className="p-8 text-center font-semibold text-[#0b5ea2]">No bottles or reams have been manually opened yet.</td></tr>:usageEntries.map((row,index)=><tr key={`${row.created_at}-${index}`} className="text-[#0b5ea2]"><td className="whitespace-nowrap px-3 py-3">{new Date(row.created_at).toLocaleString()}</td><td className="px-3 py-3">{row.supply_type}</td><td className="px-3 py-3 font-semibold">{row.supply_name}</td><td className="px-3 py-3">{row.activity_code==='LoadedIntoPrinter'?'Bottle loaded':'Ream opened'}</td><td className="px-3 py-3">{whole(row.quantity)} {row.unit}</td><td className="px-3 py-3">{whole(row.balance_before)}</td><td className="px-3 py-3">{whole(row.balance_after)}</td><td className="px-3 py-3">{row.recorded_by??'System'}</td></tr>)}</tbody></table></div></SectionCard>
    {usage&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-[#0b5ea2]/60 p-4" role="dialog" aria-modal="true"><div className="w-full max-w-md rounded-2xl bg-[#FFFFFF] p-6 shadow-2xl"><h2 className="text-xl font-bold text-[#0b5ea2]">{usage.kind==='ink'?'Load one ink bottle':'Open one paper ream'}</h2><p className="mt-2 text-sm text-[#0b5ea2]/70">{usage.name} currently has <b>{usage.current}</b> unopened {usage.kind==='ink'?'bottles':'reams'}. This deducts exactly one and records today’s date and your account.</p><div className="mt-6 flex justify-end gap-2"><Button variant="secondary" onClick={()=>setUsage(null)}>Cancel</Button><Button disabled={saving} onClick={()=>void confirmUsage()}>{saving?'Saving…':'Confirm usage'}</Button></div></div></div>}
    {selected&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-[#0b5ea2]/60 p-4" role="dialog" aria-modal="true"><form onSubmit={submitRestock} className="w-full max-w-md rounded-2xl bg-[#FFFFFF] p-6 shadow-2xl"><h2 className="text-xl font-bold text-[#0b5ea2]">{selected.kind==='paper'?'Restock paper':'Restock ink bottles'}</h2><p className="mt-1 text-sm text-[#0b5ea2]/65">{selected.name} · Current stock: {selected.current} {selected.unit}</p><div className="mt-5 space-y-4"><label className="block text-xs font-bold text-[#0b5ea2]">{selected.kind==='paper'?'Reams to add':'Bottles to add'}<input required className={input} type="number" min="1" max="10000" step="1" value={quantity} onChange={e=>setQuantity(Number(e.target.value))}/></label><label className="block text-xs font-bold text-[#0b5ea2]">{selected.kind==='paper'?'Cost per ream':'Cost per bottle'}<input required className={input} type="number" min="0.01" max="1000000" step="0.01" value={unitCost} onChange={e=>setUnitCost(e.target.value)}/></label><div className="rounded-xl bg-[#FFF200]/35 p-3 text-sm text-[#0b5ea2]">Total restocking expense: <b>{money(totalExpense)}</b></div></div><div className="mt-6 flex justify-end gap-2"><Button variant="secondary" onClick={()=>setSelected(null)}>Cancel</Button><Button type="submit" disabled={saving}>{saving?'Saving…':selected.kind==='paper'?'Add paper stock':'Add bottles'}</Button></div></form></div>}
    {showInk&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-[#0b5ea2]/60 p-4" role="dialog" aria-modal="true"><form onSubmit={addInk} className="w-full max-w-lg rounded-2xl bg-[#FFFFFF] p-6"><h2 className="text-xl font-bold text-[#0b5ea2]">Add ink bottle stock</h2><div className="mt-5 grid gap-3 sm:grid-cols-2"><label className="text-xs font-bold text-[#0b5ea2]">Ink type<input required className={input} value={newInk.cartridge_type} onChange={e=>setNewInk(value=>({...value,cartridge_type:e.target.value}))}/></label><label className="text-xs font-bold text-[#0b5ea2]">Color<select className={input} value={newInk.color_variation} onChange={e=>setNewInk(value=>({...value,color_variation:e.target.value}))}>{['Black','Cyan','Magenta','Yellow'].map(color=><option key={color}>{color}</option>)}</select></label><label className="text-xs font-bold text-[#0b5ea2]">Number of bottles<input required className={input} type="number" min="1" max="10000" step="1" value={newInk.available_bottles} onChange={e=>setNewInk(value=>({...value,available_bottles:Number(e.target.value)}))}/></label><label className="text-xs font-bold text-[#0b5ea2]">Cost per bottle<input required className={input} type="number" min="0.01" max="1000000" step="0.01" value={newInk.cost_per_bottle} onChange={e=>setNewInk(value=>({...value,cost_per_bottle:e.target.value}))}/></label></div><div className="mt-4 rounded-xl bg-[#FFF200]/35 p-3 text-sm text-[#0b5ea2]">Total restocking expense: <b>{money(newInk.available_bottles*Number(newInk.cost_per_bottle||0))}</b></div><div className="mt-6 flex justify-end gap-2"><Button variant="secondary" onClick={()=>setShowInk(false)}>Cancel</Button><Button type="submit" disabled={saving}>{saving?'Saving…':'Add ink stock'}</Button></div></form></div>}
  </>
}
